CC=~/llvm-mos/bin/mos-c128-clang
CFLAGS=-O1 -flto -fnonreentrant -Wall -DTINY -DNO_GRAPHICS -DC128

all: 8086tiny loadram

8086tiny: 8086tiny.c georam.c
	$(CC) 8086tiny.c georam.c -o 8086tiny $(CFLAGS)

loadram: loadram.c georam.c
	$(CC) loadram.c georam.c -o loadram $(CFLAGS)

clean:
	rm 8086tiny loadram
