CC=~/llvm-mos/bin/mos-c64-clang
CFLAGS=-O1 -flto -fnonreentrant -mcpu=w65816 -Wall -DTINY -DNO_GRAPHICS

all: 8086tiny loadram

8086tiny: 8086tiny.c w65816.c
	$(CC) 8086tiny.c w65816.c -o 8086tiny $(CFLAGS)

loadram: loadram.c w65816.c
	$(CC) loadram.c w65816.c -o loadram $(CFLAGS)

clean:
	rm 8086tiny loadram
